name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        repository: danielga/garrysmod_common
        ref: x86-64-support-sourcesdk
        path: 'garrysmod_common'
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: coreutils g++-multilib
        version: 1.0
    - name: Install Premake
      run: |
        wget -qO- https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz | sudo tar -xzm --no-same-owner --directory=/usr/bin
        chmod +x /usr/bin/premake5
    - name: Generate Project
      run: |
        sudo premake5 --gmcommon=garrysmod_common gmake
    - name: Make
      run: |
        cd projects/linux/gmake
        sudo make
        sudo make config=releasewithsymbols_x86_64
    - uses: actions/upload-artifact@v4
      with:
        name: gmsv_cmdremover_linux.dll
        path: projects/linux/gmake/x86/ReleaseWithSymbols/gmsv_cmdremover_linux.dll
    - uses: actions/upload-artifact@v4
      with:
        name: gmsv_cmdremover_linux64.dll
        path: projects/linux/gmake/x86_64/ReleaseWithSymbols/gmsv_cmdremover_linux64.dll
